### ISSUE TITLE
Webpart reports it cannot find the list

### ISSUE THREAD

**Issue by NPrice99** [vman/spfx-sitepage-comments#1]
Hi

WIll _api/web/lists('1aaec881-7f5b-4f82-b1f7-9e02cc116098')/GetItemById(3)/Comments always find the Comments list ?

I keep getting  HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(Fetch)GET - https://Tenant.sharepoint.com/sites/CommunicationsSite/_api/web/lists('1aaec881-7f5b-4f82-b1f7-9e02cc116098')/GetItemById(3)/Comments 

Regards

Nigel

**Comment by vman** [comment]
Hi @NPrice99, I am closing this issuse as we resolved it here: http://www.vrdmn.com/2017/07/working-with-page-comments-rest-api-in.html?showComment=1517707595089#c6660166856744949648
